apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-multiclusterhub-manager
rules:
  - apiGroups:
      - operator.open-cluster-management.io
    resources:
      - multiclusterhubs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
