apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - argocd-multiclusterhub-manager-clusterrole.yaml
  - argocd-multiclusterhub-manager-rolebinding.yaml
