apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nnsaraiya/acm-install-aws.git
    targetRevision: main
    path: operator/overlays/aws-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
