apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-install-aws-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/nnsaraiya/acm-install-aws.git
    targetRevision: main
    path: gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
